import type { Locale } from "./format"

/** key -> [fa, en] */
export const dict = {
	brand_tagline: ["پنل ابری مدیریت نمایندگی VPN", "VPN Reseller Cloud"],
	nav_dashboard: ["داشبورد", "Dashboard"],
	nav_clients: ["کلاینت‌ها", "Clients"],
	nav_servers: ["سرورها", "Servers"],
	nav_admins: ["ادمین‌ها", "Admins"],
	nav_audit: ["لاگ رخدادها", "Audit log"],
	nav_settings: ["تنظیمات", "Settings"],
	logout: ["خروج", "Log out"],
	owner: ["مالک", "Owner"],
	admin: ["ادمین", "Admin"],
	search: ["جستجو…", "Search…"],
	save: ["ذخیره", "Save"],
	cancel: ["لغو", "Cancel"],
	delete: ["حذف", "Delete"],
	edit: ["ویرایش", "Edit"],
	create: ["ایجاد", "Create"],
	close: ["بستن", "Close"],
	copy: ["کپی", "Copy"],
	copied: ["کپی شد", "Copied"],
	loading: ["در حال بارگذاری…", "Loading…"],
	confirm_delete: ["مطمئنید؟ این عمل قابل بازگشت نیست.", "Are you sure? This cannot be undone."],
	nothing_here: ["هنوز چیزی اینجا نیست", "Nothing here yet"],
	error_generic: ["خطایی رخ داد", "Something went wrong"],
	unlimited: ["نامحدود", "Unlimited"],
	never: ["همیشگی", "Never"],
	days: ["روز", "days"],
	day_short: ["روز", "d"],
	all: ["همه", "All"],
	status: ["وضعیت", "Status"],
	name: ["نام", "Name"],
	actions: ["عملیات", "Actions"],
	yes: ["بله", "Yes"],
	no: ["خیر", "No"],
	active: ["فعال", "Active"],
	inactive: ["غیرفعال", "Inactive"],
	enabled: ["فعال", "Enabled"],
	disabled: ["غیرفعال", "Disabled"],
	theme_toggle: ["تغییر تم", "Toggle theme"],
	language: ["زبان", "Language"],

	// statuses
	st_ACTIVE: ["فعال", "Active"],
	st_DISABLED: ["غیرفعال", "Disabled"],
	st_EXPIRED: ["منقضی", "Expired"],
	st_LIMITED: ["حجم تمام", "Out of data"],
	st_ONLINE: ["آنلاین", "Online"],
	st_OFFLINE: ["آفلاین", "Offline"],
	st_UNKNOWN: ["نامشخص", "Unknown"],
	st_AUTH_ERROR: ["خطای ورود", "Auth error"],

	// login
	login_title: ["ورود به پنل", "Sign in"],
	login_sub: ["برای ادامه وارد حساب خود شوید", "Sign in to your account to continue"],
	username: ["نام کاربری", "Username"],
	password: ["رمز عبور", "Password"],
	totp_code: ["کد تأیید دومرحله‌ای", "Two-factor code"],
	totp_hint: ["کد ۶ رقمی برنامهٔ Authenticator را وارد کنید", "Enter the 6-digit code from your authenticator app"],
	sign_in: ["ورود", "Sign in"],
	login_invalid: ["نام کاربری یا رمز عبور نادرست است", "Invalid username or password"],
	login_disabled: ["حساب شما غیرفعال یا منقضی شده است", "Your account is disabled or expired"],
	login_totp_invalid: ["کد تأیید نادرست است", "Invalid two-factor code"],

	// dashboard
	dash_welcome: ["خوش آمدید", "Welcome back"],
	dash_clients_total: ["کل کلاینت‌ها", "Total clients"],
	dash_online_now: ["آنلاین اکنون", "Online now"],
	dash_active: ["فعال", "Active"],
	dash_expiring: ["رو به انقضا (۳ روز)", "Expiring (3 days)"],
	dash_servers: ["سرورها", "Servers"],
	dash_traffic_today: ["مصرف امروز", "Traffic today"],
	dash_traffic_total: ["مصرف کل", "Total used"],
	dash_usage_14d: ["مصرف ۱۴ روز گذشته", "Usage — last 14 days"],
	dash_server_health: ["سلامت سرورها", "Server health"],
	dash_recent_clients: ["کلاینت‌های اخیر", "Recent clients"],
	dash_quota: ["سهمیهٔ شما", "Your quota"],
	dash_allocated: ["تخصیص‌داده", "Allocated"],
	dash_admins: ["ادمین‌ها", "Admins"],
	upload: ["آپلود", "Upload"],
	download: ["دانلود", "Download"],
	cpu: ["پردازنده", "CPU"],
	memory: ["رم", "RAM"],
	last_seen: ["آخرین ارتباط", "Last seen"],

	// servers
	srv_title: ["سرورها", "Servers"],
	srv_sub: ["پنل‌های 3x-ui متصل به SRPanel", "3x-ui panels connected to SRPanel"],
	srv_add: ["افزودن سرور", "Add server"],
	srv_edit: ["ویرایش سرور", "Edit server"],
	srv_name: ["نام نمایشی", "Display name"],
	srv_url: ["آدرس پنل (با پورت و مسیر)", "Panel URL (with port & path)"],
	srv_user: ["نام کاربری پنل", "Panel username"],
	srv_pass: ["رمز عبور پنل", "Panel password"],
	srv_pass_keep: ["خالی بگذارید تا تغییر نکند", "Leave blank to keep"],
	srv_public_host: ["هاست عمومی برای لینک‌ها (اختیاری)", "Public host for links (optional)"],
	srv_weight: ["وزن (توزیع بار)", "Weight (load balancing)"],
	srv_test: ["تست اتصال", "Test connection"],
	srv_test_ok: ["اتصال موفق — {n} اینباند پیدا شد", "Connected — {n} inbounds found"],
	srv_sync: ["همگام‌سازی", "Sync now"],
	srv_inbounds: ["اینباندها", "Inbounds"],
	srv_clients: ["کلاینت", "clients"],
	srv_empty: ["هنوز سروری اضافه نکرده‌اید. اولین پنل 3x-ui را متصل کنید.", "No servers yet. Connect your first 3x-ui panel."],
	srv_delete_warn: ["حذف سرور، اتصال کلاینت‌ها به آن را حذف می‌کند (کلاینت‌ها روی پنل دست‌نخورده می‌مانند).", "Deleting a server removes its client links (clients on the panel are left untouched)."],
	last_error: ["آخرین خطا", "Last error"],

	// clients
	cl_title: ["کلاینت‌ها", "Clients"],
	cl_sub: ["مدیریت اشتراک‌ها روی همهٔ سرورها از یک جا", "Manage subscriptions across all servers in one place"],
	cl_add: ["کلاینت جدید", "New client"],
	cl_edit: ["ویرایش کلاینت", "Edit client"],
	cl_name_ph: ["مثلاً ali-iphone", "e.g. ali-iphone"],
	cl_traffic_gb: ["حجم (گیگابایت، ۰ = نامحدود)", "Data (GB, 0 = unlimited)"],
	cl_days: ["مدت (روز، ۰ = همیشگی)", "Duration (days, 0 = never)"],
	cl_ip_limit: ["محدودیت IP (۰ = بدون محدودیت)", "IP limit (0 = none)"],
	cl_note: ["یادداشت", "Note"],
	cl_phone: ["موبایل", "Phone"],
	cl_telegram: ["آیدی تلگرام", "Telegram ID"],
	cl_targets: ["سرورها و اینباندها", "Servers & inbounds"],
	cl_targets_hint: ["کلاینت روی همهٔ موارد انتخاب‌شده ساخته می‌شود و یک لینک اشتراک می‌گیرد", "The client is created on every selected inbound and gets one subscription link"],
	cl_usage: ["مصرف", "Usage"],
	cl_expiry: ["انقضا", "Expiry"],
	cl_servers: ["سرورها", "Servers"],
	cl_sub_link: ["لینک اشتراک", "Subscription link"],
	cl_sub_page: ["صفحهٔ اشتراک", "Subscription page"],
	cl_reset: ["ریست ترافیک", "Reset traffic"],
	cl_extend: ["تمدید", "Extend"],
	cl_extend_days: ["چند روز تمدید شود؟", "Extend by how many days?"],
	cl_enable: ["فعال کردن", "Enable"],
	cl_disable: ["غیرفعال کردن", "Disable"],
	cl_links: ["لینک‌های کانفیگ", "Config links"],
	cl_qr: ["کد QR", "QR code"],
	cl_usage_30d: ["مصرف ۳۰ روز گذشته", "Usage — last 30 days"],
	cl_created: ["تاریخ ساخت", "Created"],
	cl_online: ["آخرین آنلاین", "Last online"],
	cl_empty: ["هنوز کلاینتی نساخته‌اید.", "No clients yet."],
	cl_partial_error: ["کلاینت ساخته شد اما روی برخی سرورها خطا داشت:", "Client saved but some servers failed:"],
	cl_owner: ["ادمین", "Admin"],

	// admins
	ad_title: ["ادمین‌ها", "Admins"],
	ad_sub: ["نماینده‌ها و سهمیهٔ آن‌ها", "Resellers and their quotas"],
	ad_add: ["ادمین جدید", "New admin"],
	ad_edit: ["ویرایش ادمین", "Edit admin"],
	ad_display: ["نام نمایشی", "Display name"],
	ad_quota_gb: ["سهمیهٔ ترافیک (GB، خالی = نامحدود)", "Traffic quota (GB, blank = unlimited)"],
	ad_client_limit: ["سقف کلاینت (خالی = نامحدود)", "Client limit (blank = unlimited)"],
	ad_expires: ["انقضای حساب (خالی = همیشگی)", "Account expiry (blank = never)"],
	ad_access: ["دسترسی به سرورها", "Server access"],
	ad_access_hint: ["سرورهایی که این ادمین می‌تواند روی آن‌ها کلاینت بسازد", "Servers this admin may create clients on"],
	ad_new_pass: ["رمز جدید (اختیاری)", "New password (optional)"],
	ad_allocated: ["تخصیص", "Allocated"],
	ad_used: ["مصرف", "Used"],
	ad_clients: ["کلاینت‌ها", "Clients"],
	ad_last_login: ["آخرین ورود", "Last login"],

	// settings
	set_title: ["تنظیمات", "Settings"],
	set_profile: ["حساب کاربری", "Account"],
	set_change_pass: ["تغییر رمز عبور", "Change password"],
	set_current_pass: ["رمز فعلی", "Current password"],
	set_new_pass: ["رمز جدید", "New password"],
	set_pass_changed: ["رمز عبور تغییر کرد", "Password changed"],
	set_2fa: ["ورود دومرحله‌ای (2FA)", "Two-factor authentication"],
	set_2fa_on: ["فعال است", "Enabled"],
	set_2fa_off: ["غیرفعال است", "Disabled"],
	set_2fa_start: ["فعال‌سازی 2FA", "Enable 2FA"],
	set_2fa_scan: ["این کد را با Google Authenticator یا مشابه اسکن کنید و کد ۶ رقمی را وارد کنید", "Scan with Google Authenticator (or similar) and enter the 6-digit code"],
	set_2fa_confirm: ["تأیید و فعال‌سازی", "Confirm & enable"],
	set_2fa_disable: ["غیرفعال کردن 2FA", "Disable 2FA"],
	set_2fa_enabled_msg: ["ورود دومرحله‌ای فعال شد", "Two-factor authentication enabled"],
	set_brand: ["برندینگ", "Branding"],
	set_brand_hint: ["نام و رنگ‌هایی که در صفحهٔ اشتراک مشتریان نمایش داده می‌شود", "Name and colors shown on the customer subscription page"],
	set_brand_name: ["نام برند", "Brand name"],
	set_brand_tagline: ["شعار", "Tagline"],
	set_brand_logo: ["آدرس لوگو (URL)", "Logo URL"],
	set_brand_primary: ["رنگ اصلی", "Primary color"],
	set_brand_accent: ["رنگ تأکیدی", "Accent color"],
	set_brand_support: ["لینک پشتیبانی", "Support URL"],
	set_brand_telegram: ["لینک تلگرام", "Telegram URL"],
	set_saved: ["ذخیره شد", "Saved"],
	set_appearance: ["ظاهر و زبان", "Appearance & language"],

	// audit
	au_title: ["لاگ رخدادها", "Audit log"],
	au_sub: ["هر اتفاق مهمی که در پنل رخ می‌دهد", "Everything important that happens in the panel"],
	au_time: ["زمان", "Time"],
	au_actor: ["کاربر", "Actor"],
	au_action: ["عمل", "Action"],
	au_target: ["هدف", "Target"],
	au_ip: ["IP", "IP"],

	// sub page
	sub_title: ["اشتراک شما", "Your subscription"],
	sub_remaining: ["باقی‌مانده", "Remaining"],
	sub_used: ["مصرف‌شده", "Used"],
	sub_expires: ["انقضا", "Expires"],
	sub_copy_link: ["کپی لینک اشتراک", "Copy subscription link"],
	sub_add_to: ["افزودن به برنامه", "Add to app"],
	sub_configs: ["کانفیگ‌ها", "Configs"],
	sub_apps: ["برنامه‌های پیشنهادی", "Recommended apps"],
	sub_support: ["پشتیبانی", "Support"],
	sub_scan: ["با برنامهٔ خود اسکن کنید", "Scan with your app"],
	/* --- additions (pages) --- */
	confirm: ["تأیید", "Confirm"],
	ad_username: ["نام کاربری", "Username"],
	ad_password: ["رمز عبور", "Password"],
	ad_display_name: ["نام نمایشی", "Display name"],
	ad_quota: ["سهمیه ترافیک", "Traffic quota"],
	ad_servers: ["دسترسی سرورها", "Server access"],
	ad_blank_unlimited: ["خالی = نامحدود", "Blank = unlimited"],
	ad_server_access: ["دسترسی به سرورها و اینباندها", "Server & inbound access"],
	ad_server_access_hint: ["سرورهایی که این ادمین می‌تواند روی آن‌ها کلاینت بسازد. بدون انتخاب اینباند = همه اینباندها.", "Servers this admin can create clients on. No inbound selected = all inbounds."],
	ad_all_inbounds: ["همه اینباندها", "All inbounds"],
	au_meta: ["جزئیات", "Details"],
	set_account: ["حساب کاربری", "Account"],
	set_password: ["تغییر رمز عبور", "Change password"],
	set_pw_current: ["رمز فعلی", "Current password"],
	set_pw_new: ["رمز جدید", "New password"],
	set_pw_confirm: ["تکرار رمز جدید", "Confirm new password"],
	set_pw_mismatch: ["رمز جدید و تکرار آن یکسان نیستند", "Passwords do not match"],
	set_pw_changed: ["رمز عبور با موفقیت تغییر کرد", "Password changed"],
	set_2fa_hint: ["با فعال‌سازی تأیید دومرحله‌ای، هنگام ورود یک کد ۶ رقمی از Google Authenticator یا برنامه مشابه لازم است.", "With 2FA enabled, a 6-digit code from Google Authenticator (or similar) is required at login."],
	set_2fa_enable: ["فعال‌سازی 2FA", "Enable 2FA"],
	set_2fa_enabled: ["تأیید دومرحله‌ای فعال شد", "Two-factor authentication enabled"],
	set_2fa_disabled: ["تأیید دومرحله‌ای غیرفعال شد", "Two-factor authentication disabled"],
	/* ---------- stage 2A ---------- */
	nav_monitoring: ["مانیتورینگ", "Monitoring"],
	nav_backups: ["بکاپ‌ها", "Backups"],
	nav_integrations: ["یکپارچه‌سازی", "Integrations"],
	refresh: ["بروزرسانی", "Refresh"],
	created_at: ["تاریخ ایجاد", "Created"],
	/* monitoring */
	mon_title: ["مانیتورینگ سرورها", "Server monitoring"],
	mon_sub: ["آپ‌تایم، تأخیر، منابع و رخدادهای قطعی به صورت زنده", "Live uptime, latency, resources and incidents"],
	mon_auto_refresh: ["بروزرسانی خودکار", "Auto refresh"],
	mon_servers_online: ["سرورهای آنلاین", "Servers online"],
	mon_uptime_24h: ["آپ‌تایم ۲۴ ساعت", "Uptime 24h"],
	mon_uptime_7d: ["آپ‌تایم ۷ روز", "Uptime 7d"],
	mon_open_incidents: ["رخدادهای باز", "Open incidents"],
	mon_incident_short: ["رخداد", "incident(s)"],
	mon_latency_24h: ["تأخیر پاسخ (۲۴ ساعت)", "Latency (24h)"],
	mon_no_data: ["هنوز داده‌ای ثبت نشده", "No data yet"],
	mon_no_servers: ["سروری برای مانیتورینگ وجود ندارد", "No servers to monitor"],
	mon_incidents: ["رخدادها (Incidents)", "Incidents"],
	mon_incidents_sub: ["قطعی، خطای احراز هویت، توقف Xray و CPU بالا به صورت خودکار ثبت و به تلگرام ارسال می‌شود", "Outages, auth errors, Xray down and high CPU are recorded and pushed to Telegram"],
	mon_filter_all: ["همه", "All"],
	mon_filter_open: ["باز", "Open"],
	mon_filter_resolved: ["برطرف‌شده", "Resolved"],
	mon_no_incidents: ["رخدادی وجود ندارد — همه‌چیز سبز است 🎉", "No incidents — all green 🎉"],
	mon_col_server: ["سرور", "Server"],
	mon_col_kind: ["نوع", "Kind"],
	mon_col_status: ["وضعیت", "Status"],
	mon_col_started: ["شروع", "Started"],
	mon_col_duration: ["مدت", "Duration"],
	mon_col_message: ["پیام", "Message"],
	mon_resolve: ["برطرف شد", "Resolve"],
	mon_resolve_confirm: ["این رخداد به صورت دستی برطرف‌شده علامت بزنیم؟", "Mark this incident as resolved manually?"],
	mon_resolved: ["رخداد برطرف‌شده علامت خورد", "Incident resolved"],
	inc_OFFLINE: ["قطعی سرور", "Offline"],
	inc_AUTH_ERROR: ["خطای ورود به پنل", "Auth error"],
	inc_XRAY_DOWN: ["Xray متوقف", "Xray down"],
	inc_HIGH_CPU: ["CPU بالا", "High CPU"],
	/* backups */
	bk_title: ["بکاپ دیتابیس", "Database backups"],
	bk_sub: ["بکاپ زمان‌بندی‌شده و دستی از کل پنل + ارسال خودکار به تلگرام", "Scheduled & manual full-panel backups with Telegram upload"],
	bk_run_now: ["بکاپ فوری", "Back up now"],
	bk_done: ["بکاپ با موفقیت ساخته شد", "Backup completed"],
	bk_failed: ["بکاپ ناموفق بود", "Backup failed"],
	bk_deleted: ["بکاپ حذف شد", "Backup deleted"],
	bk_stat_count: ["بکاپ‌های سالم", "Healthy backups"],
	bk_stat_disk: ["فضای اشغال‌شده", "Disk used"],
	bk_stat_last: ["آخرین بکاپ موفق", "Last successful"],
	bk_files: ["فایل", "files"],
	bk_sent_tg: ["به تلگرام ارسال شد", "Sent to Telegram"],
	bk_schedule: ["زمان‌بندی", "Schedule"],
	bk_schedule_sub: ["بکاپ روزانه در ساعت مشخص (به وقت سرور / SRP_TZ)", "Daily backup at the given hour (server time / SRP_TZ)"],
	bk_enabled: ["بکاپ خودکار روزانه", "Daily automatic backup"],
	bk_hour: ["ساعت اجرا", "Run at"],
	bk_hour_hint: ["بهتر است ساعتی کم‌ترافیک انتخاب کنید", "Pick a low-traffic hour"],
	bk_keep_last: ["نگه‌داری آخرین N بکاپ", "Keep last N backups"],
	bk_send_tg: ["ارسال فایل بکاپ به تلگرام", "Upload backup file to Telegram"],
	bk_list: ["فهرست بکاپ‌ها", "Backup files"],
	bk_empty: ["هنوز بکاپی ساخته نشده", "No backups yet"],
	bk_col_file: ["فایل", "File"],
	bk_col_status: ["وضعیت", "Status"],
	bk_col_size: ["حجم", "Size"],
	bk_col_trigger: ["نوع", "Trigger"],
	bk_col_date: ["تاریخ", "Date"],
	bk_status_OK: ["موفق", "OK"],
	bk_status_FAILED: ["ناموفق", "Failed"],
	bk_status_RUNNING: ["در حال اجرا", "Running"],
	bk_trigger_scheduled: ["زمان‌بندی", "Scheduled"],
	bk_trigger_manual: ["دستی", "Manual"],
	bk_trigger_telegram: ["تلگرام", "Telegram"],
	bk_download: ["دانلود", "Download"],
	bk_restore: ["بازگردانی (Restore)", "Restore"],
	bk_restore_sub: ["روی سرور، فایل بکاپ را با دستورات زیر برگردانید", "Run these commands on the server to restore a file"],
	/* telegram */
	tg_title: ["بات تلگرام", "Telegram bot"],
	tg_sub: ["توکن بات را از @BotFather بگیرید و بات را به گروه/کانال مدیریت اضافه کنید", "Create a bot with @BotFather and add it to your admin group/channel"],
	tg_enabled: ["ارسال اعلان از طریق تلگرام", "Send notifications via Telegram"],
	tg_token: ["توکن بات", "Bot token"],
	tg_token_hint: ["مثل 123456789:AAxxxxxxxx — رمزنگاری‌شده ذخیره می‌شود", "e.g. 123456789:AAxxxxxxxx — stored server-side"],
	tg_token_saved: ["توکن فعلی", "Current token"],
	tg_chat_id: ["Chat ID مدیریت", "Admin chat ID"],
	tg_chat_hint: ["به بات دستور /id بفرستید تا شناسه را بگیرید (گروه‌ها با -100 شروع می‌شوند)", "Send /id to the bot to get it (groups start with -100)"],
	tg_bot_enabled: ["فعال‌بودن دستورات بات (/status و …)", "Enable bot commands (/status …)"],
	tg_test: ["تست اتصال", "Test connection"],
	tg_test_ok: ["پیام تست با موفقیت ارسال شد", "Test message sent"],
	tg_test_fail: ["توکن نامعتبر است", "Invalid token"],
	tg_bot_ok_no_msg: ["بات معتبر است اما پیام ارسال نشد", "Bot is valid but message failed"],
	tg_notifications: ["چه چیزهایی اطلاع داده شود؟", "What to notify"],
	tg_notifications_sub: ["ادمین‌ها با تنظیم «آی‌دی تلگرام» فقط اعلان مربوط به کلاینت‌های خود را می‌گیرند", "Admins with a Telegram ID only get alerts about their own clients"],
	tg_notify_incidents: ["رخدادهای سرور (قطعی / برطرف شدن)", "Server incidents (down / recovered)"],
	tg_notify_backups: ["نتیجه بکاپ‌ها", "Backup results"],
	tg_notify_expiry: ["یادآوری انقضای کلاینت‌ها", "Client expiry reminders"],
	tg_notify_traffic: ["هشدار اتمام ترافیک", "Traffic usage warnings"],
	tg_notify_logins: ["ورود و ورود ناموفق ادمین‌ها", "Admin logins & failed logins"],
	tg_notify_clients_direct: ["پیام مستقیم به کلاینت‌هایی که آی‌دی تلگرام دارند", "Message clients that have a Telegram ID directly"],
	tg_commands: ["دستورات بات", "Bot commands"],
	tg_commands_hint: ["فقط مالک و ادمین‌هایی که آی‌دی تلگرام‌شان در پنل ثبت شده می‌توانند از بات استفاده کنند", "Only the owner and admins whose Telegram ID is set in the panel can use the bot"],
	/* api keys */
	ak_title: ["کلیدهای API", "API keys"],
	ak_sub: ["دسترسی برنامه‌نویسی به کلاینت‌ها و سرورهای شما (برای بات‌ها، فروشگاه و اتوماسیون)", "Programmatic access to your clients & servers (bots, shops, automation)"],
	ak_create: ["کلید جدید", "New key"],
	ak_name: ["نام", "Name"],
	ak_prefix: ["پیشوند", "Prefix"],
	ak_scopes: ["دسترسی", "Scopes"],
	ak_scope_write: ["اجازه نوشتن (ساخت/ویرایش/حذف کلاینت)", "Write access (create/update/delete clients)"],
	ak_scope_hint: ["بدون این گزینه، کلید فقط اجازه خواندن دارد", "Without it the key is read-only"],
	ak_created_once: ["کلید ساخته شد — فقط یک بار نمایش داده می‌شود", "Key created — shown only once"],
	ak_created_once_hint: ["این کلید را همین حالا کپی و در جای امنی نگه‌دارید. بعد از بستن این پنجره دیگر قابل مشاهده نیست.", "Copy it now and store it safely. It cannot be shown again."],
	ak_revoke: ["ابطال", "Revoke"],
	ak_revoke_confirm: ["این کلید بلافاصله بی‌اعتبار می‌شود. ادامه؟", "This key stops working immediately. Continue?"],
	ak_revoked: ["کلید باطل شد", "Key revoked"],
	ak_revoked_badge: ["باطل‌شده", "revoked"],
	ak_last_used: ["آخرین استفاده", "Last used"],
	ak_empty: ["هنوز کلیدی ساخته نشده", "No API keys yet"],
	ak_curl_hint: ["نمونه استفاده (REST v1)", "Usage example (REST v1)"],
	/* webhooks */
	wh_title: ["وب‌هوک‌ها", "Webhooks"],
	wh_sub: ["رویدادهای پنل به صورت POST امضاشده به سرویس شما ارسال می‌شود (با تلاش مجدد خودکار)", "Panel events are POSTed to your endpoint, signed, with automatic retries"],
	wh_create: ["وب‌هوک جدید", "New webhook"],
	wh_edit: ["ویرایش وب‌هوک", "Edit webhook"],
	wh_url: ["آدرس (URL)", "URL"],
	wh_events: ["رویدادها", "Events"],
	wh_events_hint: ["اگر هیچ رویدادی انتخاب نشود، همه رویدادها ارسال می‌شوند", "Select none to receive all events"],
	wh_all_events: ["همه رویدادها", "All events"],
	wh_active: ["فعال", "Active"],
	wh_secret: ["کلید امضا (Secret)", "Signing secret"],
	wh_secret_hint: ["با این کلید، هدر x-srp-signature را در سرویس خود اعتبارسنجی کنید", "Use it to verify the x-srp-signature header on your side"],
	wh_test: ["ارسال تست", "Send test"],
	wh_test_ok: ["تست با موفقیت دریافت شد", "Test delivered"],
	wh_test_fail: ["تست ناموفق", "Test failed"],
	wh_last_status: ["آخرین پاسخ", "Last response"],
	wh_empty: ["هنوز وب‌هوکی تعریف نشده", "No webhooks yet"],
	wh_signature_hint: ["هدرهای ارسالی", "Delivery headers"],
	/* notifications & page */
	ntf_title: ["تاریخچه اعلان‌ها", "Notification log"],
	ntf_sub: ["۱۰۰ اعلان اخیر ارسال‌شده به تلگرام", "Last 100 Telegram notifications"],
	ntf_empty: ["اعلانی ارسال نشده", "Nothing sent yet"],
	ntf_time: ["زمان", "Time"],
	ntf_kind: ["نوع", "Kind"],
	ntf_target: ["هدف", "Target"],
	ntf_result: ["نتیجه", "Result"],
	int_title: ["یکپارچه‌سازی", "Integrations"],
	int_sub: ["تلگرام، کلیدهای API، وب‌هوک و اعلان‌ها", "Telegram, API keys, webhooks and notifications"],
	int_tab_telegram: ["تلگرام", "Telegram"],
	int_tab_apikeys: ["کلیدهای API", "API keys"],
	int_tab_webhooks: ["وب‌هوک", "Webhooks"],
	int_tab_notifications: ["اعلان‌ها", "Notifications"],
	/* ---------- stage 2B: store / orders / payments / wallet ---------- */
	nav_store: ["فروشگاه", "Store"],
	nav_orders: ["سفارش‌ها", "Orders"],
	nav_wallet: ["کیف پول", "Wallet"],
	currency_irt: ["تومان", "IRT"],

	store_title_page: ["فروشگاه", "Store"],
	store_sub: ["پلن‌ها، کدهای تخفیف، روش‌های پرداخت و لینک فروشگاه اختصاصی شما", "Plans, discount codes, payment methods and your public store link"],
	store_disabled_hint: ["فروشگاه غیرفعال است — از تب تنظیمات آن را فعال کنید.", "Store is disabled — enable it from the Settings tab."],
	store_tab_overview: ["نمای کلی", "Overview"],
	store_tab_plans: ["پلن‌ها", "Plans"],
	store_tab_discounts: ["کد تخفیف", "Discounts"],
	store_tab_settings: ["تنظیمات", "Settings"],
	store_revenue_30d: ["درآمد ۳۰ روز", "Revenue (30d)"],
	store_orders_30d: ["سفارش‌های ۳۰ روز", "Orders (30d)"],
	store_link: ["لینک فروشگاه", "Store link"],
	store_no_methods: ["هیچ روش پرداختی فعال نیست", "No payment method enabled"],
	store_tg_hint: ["در بات تلگرام: /shop و لینک t.me/bot?start=store_slug — فروشگاه به‌صورت مینی‌اپ باز می‌شود.", "Telegram bot: /shop and t.me/bot?start=store_slug — opens as a Mini App."],
	store_general: ["عمومی", "General"],
	store_enabled: ["فروشگاه فعال", "Store enabled"],
	store_slug: ["نشانی (slug)", "Slug"],
	store_slug_hint: ["فقط حروف انگلیسی کوچک، عدد و خط تیره — در لینک /shop/… استفاده می‌شود", "Lowercase letters, digits, dashes — used in /shop/…"],
	store_title: ["عنوان فروشگاه", "Store title"],
	store_desc: ["توضیح کوتاه", "Short description"],
	store_rules: ["قوانین فروشگاه", "Store rules"],
	store_rules_hint: ["در صورت پر کردن، مشتری باید قبل از خرید قوانین را تأیید کند", "If set, customers must accept before purchase"],
	store_support: ["لینک پشتیبانی", "Support link"],
	store_ttl: ["مهلت پرداخت (دقیقه)", "Payment window (min)"],
	store_ttl_hint: ["سفارش‌های پرداخت‌نشده بعد از این مدت منقضی می‌شوند", "Unpaid orders expire after this"],
	store_req_tg: ["شناسه تلگرام اجباری", "Require Telegram ID"],
	store_req_phone: ["شماره موبایل اجباری", "Require phone"],

	pay_m_USDT: ["تتر (USDT)", "USDT"],
	pay_m_CARD: ["کارت به کارت", "Card transfer"],
	pay_m_ZARINPAL: ["زرین‌پال", "Zarinpal"],
	pay_m_WALLET: ["کیف پول", "Wallet"],
	pay_m_MANUAL: ["دستی", "Manual"],
	pay_usdt_sub: ["دریافت USDT در شبکه TRC20 با تأیید خودکار از بلاکچین", "Receive USDT on TRC20 with on-chain auto-verification"],
	pay_usdt_address: ["آدرس ولت (TRC20)", "Wallet address (TRC20)"],
	pay_usdt_network: ["شبکه", "Network"],
	pay_usdt_rate: ["نرخ تتر (تومان)", "USDT rate (IRT)"],
	pay_usdt_rate_hint: ["مبلغ سفارش ÷ این نرخ = مبلغ USDT", "Order amount ÷ rate = USDT amount"],
	pay_usdt_auto: ["تأیید خودکار با TXID", "Auto-verify by TXID"],
	pay_card_sub: ["مشتری رسید واریز را ارسال می‌کند و شما تأیید می‌کنید", "Customer submits a receipt; you confirm"],
	pay_card_number: ["شماره کارت", "Card number"],
	pay_card_holder: ["نام صاحب کارت", "Card holder"],
	pay_card_bank: ["بانک", "Bank"],
	pay_zp_sub: ["درگاه بانکی آنلاین — تحویل خودکار پس از پرداخت", "Online bank gateway — auto delivery"],
	pay_zp_merchant: ["Merchant ID", "Merchant ID"],
	pay_zp_saved: ["ذخیره شده", "saved"],
	pay_zp_merchant_hint: ["برای تغییر، مقدار جدید را وارد کنید. خالی = بدون تغییر", "Enter a new value to replace. Blank = keep"],
	pay_zp_sandbox: ["حالت آزمایشی (Sandbox)", "Sandbox mode"],

	plan_name: ["پلن", "Plan"],
	plan_hint: ["هر پلن به یک یا چند اینباند متصل می‌شود؛ کلاینت پس از پرداخت روی همان اینباند ساخته می‌شود.", "Each plan targets one or more inbounds; the client is created there after payment."],
	plan_new: ["پلن جدید", "New plan"],
	plan_edit: ["ویرایش پلن", "Edit plan"],
	plan_empty: ["هنوز پلنی نساخته‌اید", "No plans yet"],
	plan_active_count: ["پلن فعال", "Active plans"],
	plan_days: ["روز", "days"],
	plan_ip: ["کاربر همزمان", "IP limit"],
	plan_sold: ["فروش", "sold"],
	plan_targets: ["اینباندهای هدف", "Target inbounds"],
	plan_targets_hint: ["در صورت انتخاب چند اینباند، همه در یک اشتراک (Multi-Sub) قرار می‌گیرند", "Multiple inbounds are bundled into one subscription"],
	plan_no_inbounds: ["این سرور اینباندی ندارد — اول Sync کنید", "No inbounds — sync the server first"],
	plan_no_servers: ["سروری در دسترس نیست", "No servers available"],
	plan_badge: ["برچسب", "Badge"],
	plan_badge_hint: ["مثل «پرفروش» یا «پیشنهادی»", "e.g. Popular"],
	plan_traffic: ["حجم (GB)", "Traffic (GB)"],
	plan_sort: ["ترتیب نمایش", "Sort order"],
	plan_price: ["قیمت (تومان)", "Price (IRT)"],
	plan_old_price: ["قیمت قبلی", "Old price"],
	plan_old_price_hint: ["برای نمایش خط‌خورده (اختیاری)", "Shown struck-through (optional)"],
	plan_desc: ["توضیح", "Description"],
	plan_visible: ["نمایش در فروشگاه", "Visible in store"],
	wal_cost: ["هزینه از کیف پول شما", "Your wallet cost"],
	wal_cost_hint: ["بر اساس قیمت واحد مالک: حجم × قیمت هر GB + مدت × قیمت هر روز", "Owner unit prices: GB × price + days × price"],

	disc_new: ["کد تخفیف جدید", "New discount"],
	disc_code: ["کد", "Code"],
	disc_percent: ["درصد", "Percent"],
	disc_amount: ["مبلغ ثابت (تومان)", "Fixed amount (IRT)"],
	disc_max_uses: ["حداکثر استفاده", "Max uses"],
	disc_expires: ["تاریخ انقضا", "Expires"],
	disc_create: ["ساخت کد", "Create"],
	disc_list: ["کدهای تخفیف", "Discount codes"],
	disc_empty: ["کد تخفیفی وجود ندارد", "No discount codes"],
	disc_value: ["مقدار", "Value"],
	disc_uses: ["استفاده", "Uses"],
	disc_expired: ["منقضی", "Expired"],
	disc_exhausted: ["تمام‌شده", "Exhausted"],

	ord_title_page: ["سفارش‌ها و پرداخت‌ها", "Orders & payments"],
	ord_sub: ["بررسی رسیدها، تأیید پرداخت و پیگیری تحویل", "Review receipts, confirm payments, track delivery"],
	ord_tab_orders: ["سفارش‌ها", "Orders"],
	ord_tab_payments: ["پرداخت‌ها", "Payments"],
	ord_title: ["سفارش‌ها", "Orders"],
	ord_recent: ["سفارش‌های اخیر", "Recent orders"],
	ord_search: ["جستجو (نام، تلگرام، موبایل، توکن)", "Search (name, telegram, phone, token)"],
	ord_customer: ["مشتری", "Customer"],
	ord_amount: ["مبلغ", "Amount"],
	ord_empty: ["سفارشی وجود ندارد", "No orders"],
	ord_renew: ["تمدید", "Renewal"],
	ord_open: ["صفحه سفارش", "Order page"],
	ord_manual_paid: ["ثبت پرداخت دستی", "Mark as paid"],
	ord_manual_paid_confirm: ["این سفارش به‌عنوان پرداخت‌شده ثبت و اشتراک ساخته می‌شود. ادامه؟", "Mark as paid and provision the subscription?"],
	ord_retry: ["تلاش مجدد تحویل", "Retry delivery"],
	ord_cancel_confirm: ["سفارش لغو شود؟", "Cancel this order?"],
	ord_st_PENDING: ["در انتظار پرداخت", "Pending"],
	ord_st_PAID: ["پرداخت‌شده", "Paid"],
	ord_st_FULFILLED: ["تحویل‌شده", "Fulfilled"],
	ord_st_CANCELED: ["لغو", "Canceled"],
	ord_st_EXPIRED: ["منقضی", "Expired"],

	pay_title: ["پرداخت‌ها", "Payments"],
	pay_all: ["همه", "All"],
	pay_pending_review: ["در انتظار بررسی", "Pending review"],
	pay_empty: ["پرداختی وجود ندارد", "No payments"],
	pay_kind: ["نوع", "Kind"],
	pay_kind_ORDER: ["سفارش", "Order"],
	pay_kind_TOPUP: ["شارژ کیف پول", "Wallet top-up"],
	pay_method: ["روش پرداخت", "Method"],
	pay_proof: ["مدرک پرداخت", "Proof"],
	pay_by: ["پرداخت‌کننده", "Payer"],
	pay_ref: ["شماره پیگیری", "Reference"],
	pay_card_pan: ["کارت واریزکننده", "Payer card"],
	pay_receipt_file: ["تصویر رسید", "Receipt image"],
	pay_confirm: ["تأیید پرداخت", "Confirm"],
	pay_confirmed: ["پرداخت تأیید شد", "Payment confirmed"],
	pay_reject: ["رد", "Reject"],
	pay_rejected: ["پرداخت رد شد", "Payment rejected"],
	pay_reject_title: ["رد پرداخت", "Reject payment"],
	pay_reject_note: ["دلیل (به مشتری نمایش داده می‌شود)", "Reason (shown to customer)"],
	pay_reject_hint: ["مثلاً: مبلغ واریزی مطابقت ندارد", "e.g. amount mismatch"],
	pay_st_PENDING: ["در انتظار", "Pending"],
	pay_st_REVIEW: ["در بررسی", "In review"],
	pay_st_CONFIRMED: ["تأییدشده", "Confirmed"],
	pay_st_REJECTED: ["ردشده", "Rejected"],
	pay_st_EXPIRED: ["منقضی", "Expired"],

	wal_title: ["کیف پول", "Wallet"],
	wal_sub: ["موجودی، شارژ و تاریخچه تراکنش‌های شما", "Balance, top-ups and your transaction history"],
	wal_sub_owner: ["قیمت‌گذاری واحد، موجودی نماینده‌ها و شارژ دستی", "Unit pricing, reseller balances and manual credit"],
	wal_balance: ["موجودی", "Balance"],
	wal_spent_30d: ["مصرف ۳۰ روز", "Spent (30d)"],
	wal_unit_prices: ["قیمت واحد", "Unit prices"],
	wal_billing_off: ["بدون کسر هزینه", "Billing off"],
	wal_pending_topups: ["شارژ در انتظار", "Pending top-ups"],
	wal_tab_owner: ["نماینده‌ها و قیمت‌گذاری", "Resellers & pricing"],
	wal_tab_ledger: ["تراکنش‌ها", "Ledger"],
	wal_tab_topups: ["شارژها", "Top-ups"],
	wal_topup: ["شارژ کیف پول", "Top up"],
	wal_topup_start: ["ادامه و پرداخت", "Continue to payment"],
	wal_topup_done: ["شارژ انجام شد", "Top-up completed"],
	wal_topup_review: ["پرداخت ثبت شد و پس از تأیید مالک به موجودی اضافه می‌شود", "Submitted — credited after owner confirmation"],
	wal_topups_empty: ["شارژی ثبت نشده", "No top-ups yet"],
	wal_no_methods: ["مالک هنوز روش پرداختی برای شارژ فعال نکرده است", "Owner has not enabled any top-up method"],
	wal_ledger_empty: ["تراکنشی وجود ندارد", "No transactions"],
	wal_kind: ["نوع", "Kind"],
	wal_k_TOPUP: ["شارژ", "Top-up"],
	wal_k_PURCHASE: ["خرید / ساخت کلاینت", "Purchase"],
	wal_k_REFUND: ["بازگشت", "Refund"],
	wal_k_ADJUST: ["تنظیم دستی", "Adjustment"],
	wal_note: ["توضیح", "Note"],
	wal_balance_after: ["موجودی پس از تراکنش", "Balance after"],
	wal_pricing: ["قیمت‌گذاری", "Pricing"],
	wal_pricing_sub: ["هزینه‌ای که هنگام ساخت/تمدید کلاینت از کیف پول نماینده کسر می‌شود", "Charged to a reseller's wallet on client create/renew"],
	wal_billing_enabled: ["کسر هزینه از کیف پول نماینده‌ها", "Bill resellers from wallet"],
	wal_price_gb: ["قیمت هر گیگابایت", "Price per GB"],
	wal_price_day: ["قیمت هر روز", "Price per day"],
	wal_charge_renew: ["کسر هزینه برای تمدید هم اعمال شود", "Also charge on renewal"],
	wal_credit_limit: ["سقف بدهی", "Credit limit"],
	wal_credit_limit_hint: ["نماینده تا این مقدار می‌تواند منفی شود (۰ = بدون اعتبار)", "How far a reseller may go negative (0 = none)"],
	wal_resellers: ["نماینده‌ها", "Resellers"],
	wal_resellers_sub: ["موجودی، مصرف و قیمت اختصاصی هر نماینده", "Balance, usage and per-reseller pricing"],
	wal_no_resellers: ["نماینده‌ای وجود ندارد", "No resellers"],
	wal_default_prices: ["قیمت پیش‌فرض", "Default prices"],
	wal_adjust: ["شارژ / کسر", "Adjust"],
	wal_adjust_hint: ["عدد مثبت = شارژ، عدد منفی = کسر از موجودی", "Positive = credit, negative = debit"],
	wal_price_override_hint: ["خالی = استفاده از قیمت پیش‌فرض", "Blank = use default"],

	shop_usdt_send: ["مبلغ", "Send"],
	shop_usdt_rate: ["نرخ", "Rate"],
	shop_txid: ["هش تراکنش (TXID)", "Transaction hash (TXID)"],
	shop_txid_hint: ["پس از انتقال، هش تراکنش را از کیف پول خود کپی کنید", "Copy the TX hash from your wallet after sending"],
	shop_submit_proof: ["پرداخت کردم", "I have paid"],
	shop_card_transfer: ["مبلغ", "Transfer"],
	shop_receipt_ref: ["شماره پیگیری / مرجع", "Reference number"],
	shop_receipt_ref_hint: ["شماره پیگیری روی رسید بانکی", "Tracking number on the bank receipt"],
	shop_card_pan: ["۴ رقم آخر کارت واریزکننده (اختیاری)", "Last 4 digits of payer card (optional)"],
	shop_redirecting: ["در حال انتقال به درگاه…", "Redirecting to gateway…"],
	shop_pay_gateway: ["رفتن به درگاه", "Open gateway"],
} as const

export type DictKey = keyof typeof dict

export function translate(locale: Locale, key: DictKey, vars?: Record<string, string | number>): string {
	const entry = dict[key] as readonly [string, string] | undefined
	let s: string = entry ? (locale === "fa" ? entry[0] : entry[1]) : key
	if (vars) for (const [k, v] of Object.entries(vars)) s = s.replace(`{${k}}`, String(v))
	return s
}

